---
# tasks file for apt_install
- name: Install aptitude
  apt:
     name: aptitude
     state: present
     update_cache: true
- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: present
    update_cache: true

