---
# tasks file for docker_install
- name: Install dockers pre-requisites
  apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: present
      force_apt_get: true
      update-cache: true
- name: Add Docker GPG apt Key
  apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

- name: Add Docker Repository
  apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

- name: Update apt and install docker-ce
  apt:
      name: docker-ce
      state: latest
      update_cache: true

- name: Install Docker Module for Python
  pip:
      name: 
        - docker 
        - docker-compose

- name: Chmod 777 /var/run/docker.sock
  raw: chmod 777 /var/run/docker.sock
